### ISSUE TITLE
Cross build for Scala 2.12 milestones

### ISSUE THREAD

**Issue by retronym** [scala/async#130]

**Comment by Locke** [comment]
Is this blocked by anything in particular?

**Comment by retronym** [comment]
I'd forgotten about this one. I don't think anything is blocking this. In fact async is built with nightlies of 2.12.x in Scala's community build, so it is compatible.

https://github.com/scala/community-builds/blob/2.12.x/common.conf#L80

I'll publish a release after 2.12.0-M5 is released next week.

**Comment by retronym** [comment]
I've merged support for this in #160, and will release 0.9.6 shortly with a version for 2.12.0-RC1
