### ISSUE TITLE
Include dependency information in README

### ISSUE THREAD

**Issue by dragos** [scala/async#140]
There's no mention of the Maven coordinates for including scala-async, nor the latest version. Some people might get confused (I tried `org.scala-lang` and finally I had to go to `search.maven.org` to find the proper group ID).

**Comment by retronym** [comment]
We've been switching away from having this info in text in the README's of the modules in favour of the badge.

![image](https://cloud.githubusercontent.com/assets/65551/9876669/25d04b4e-5bfb-11e5-9184-ef0d9ca195d3.png)

Which heads to a maven search:

http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-lang.modules%20a%3Ascala-async_2.11*

The motivation was to avoid a manual step in the release process of updating the README.

But I can see that the information is now somewhat hidden, we should revisit this choice, or maybe find something that have the best of both worlds.

**Comment by dragos** [comment]
Yeah, I totally missed those badges. I guess I was trained to ignore them. Feel free to ignore this ticket then.

**Comment by retronym** [comment]
I'll close this, but will still think about how we could improve the README.

/cc @lrytz
