### ISSUE TITLE
How long does await() wait?

### ISSUE THREAD

**Issue by weihsiu** [scala/async#147]
i am using scala-async with scala.js and would like to specify the timeout duration await() waits for the future to complete.  the default seems to be just 1 minute.  is there anyway to specify a different duration?

**Comment by SethTisue** [comment]
I would suggest taking this up with the Scala.js folks

**Comment by weihsiu** [comment]
my bad.  i am calling a web service inside await() and the web service is hosted on http4s which has default response idle timeout of 1 minute...

**Comment by SethTisue** [comment]
ah, ok! thanks for updating us.
